· Fix issues and improve games, emulators, info, mmedia sections. Raspberry Pi 3 ready. · Added Xump game. · Remove Minecraft script.

diff --git a/bin/ansiweather b/bin/ansiweather
--- a/bin/ansiweather
+++ b/bin/ansiweather
@@ -1,14 +1,15 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
 ###############################################################################
 #                                                                             #
-# AnsiWeather 1.00 (c) by Frederic Cambus 2014                                #
+# AnsiWeather 1.08                                                            #
+# Copyright (c) 2013-2016, Frederic Cambus                                    #
 # https://github.com/fcambus/ansiweather                                      #
 #                                                                             #
-# Created: 2013/08/29                                                         #
-# Last Updated: 2014/01/24                                                    #
+# Created: 2013-08-29                                                         #
+# Last Updated: 2016-07-26                                                    #
 #                                                                             #
-# AnsiWeather is released under the BSD 3-Clause license.                     #
+# AnsiWeather is released under the BSD 2-Clause license.                     #
 # See LICENSE file for details.                                               #
 #                                                                             #
 ###############################################################################
@@ -17,96 +18,127 @@
 
 ###[ Configuration options ]###################################################
 
-LC_NUMERIC=C
+LC_ALL=C; export LC_ALL
 
-config_file=~/.ansiweatherrc
+config_file=${ANSIWEATHERRC:-~/.ansiweatherrc}
 
-function get_config {
+get_config() {
 	ret=""
-	if [ -f $config_file ]
+	if [ -f "$config_file" ]
 	then
-		ret=$(grep "^$1:" $config_file | awk -F: '{print $2}') 
+		ret=$(grep "^$1:" "$config_file" | awk -F: '{print $2}')
 	fi
 
 	if [ "X$ret" = "X" ]
 	then
 		return 1
 	else
-		echo $ret
+		echo "$ret"
 	fi
 }
 
-fetch_cmd=$(get_config "fetch_cmd" || echo "curl -s")
+fetch_cmd=$(get_config "fetch_cmd" || echo "curl -sf")
 
 
 
-###[ Check if jq is installed ]###############################################
+###[ Parse the command line ]##################################################
 
-jqpath="`which jq`"
-
-if [ "$jqpath" == "" ]
-then 
-	echo -e "\njq binary is not found, please download it from http://stedolan.github.io/jq/ and put it in your PATH"
-	exit 255
-fi 
-
-
-
-###[ Auto-Location Logic ]####################################################
-
-geo_locate_api="http://www.telize.com/geoip" #geo location service
-
-function auto_locate {
-	ret=""
-
-	geo_data=$($fetch_cmd $geo_locate_api)
-
-	city=$(echo $geo_data | jq -r '.city')
-
-	country=$(echo $geo_data | jq -r '.country_code')
-
-	ret=$city,$country
-
-	if [ "$ret" == "," ]
-	then
-		return 1
-	else
-		echo $ret
-	fi
-}
-
-# Location : example "Moscow,RU"
-location=$(get_config "location" || auto_locate || echo "Moscow,RU")
-
-# System of Units : "metric" or "imperial"
-units=$(get_config "units" || echo "metric")
-
-# Display symbols : "true" or "false" (requires an Unicode capable display)
-symbols=$(get_config "symbols" || echo true)
-
-# Show forecast : How many days, example "5". "0" is standard output
-forecast=$(get_config "forecast" || echo 0)
-
-# Show daylight : "true" or "false"
-daylight=$(get_config "daylight" || echo false)
-
-# Or get config options from command line flags
-while getopts l:u:s:f:Fd: option
+# Get config options from command line flags
+while getopts k:l:u:f:Fd:a:s:h option
 do
 	case "${option}"
 	in
 		l) location=${OPTARG};;
 		u) units=${OPTARG};;
-		s) symbols=${OPTARG};;
 		f) forecast=${OPTARG};;
 		F) forecast="5";;
 		d) daylight=${OPTARG};;
+		a) ansi=${OPTARG};;
+		s) symbols=${OPTARG};;
+		k) api_key=${OPTARG};;
+		h) usage=true;;
 	esac
 done
 
 
 
-#### [ Colors and characters ]#################################################
+###[ Display usage ]###########################################################
+
+if [ "$usage" = true ]
+then
+	printf "%s\n" \
+		"" \
+		"AnsiWeather 1.08" \
+		"Copyright (c) 2013-2016, Frederic Cambus" \
+		"" \
+		"USAGE: ansiweather [options]" \
+		"" \
+		"Options are :" \
+		"" \
+		"	-l Specify location" \
+		"	-u Specify unit system to use (metric or imperial)" \
+		"	-f Toggle forecast mode for the specified number of upcoming days" \
+		"	-F Toggle forecast mode for the next five days" \
+		"	-d Toggle daylight data display" \
+		"	-a Toggle ANSI colors display" \
+		"	-s Toggle symbols display" \
+		"	-k OpenWeatherMap API key" \
+		"	-h Display usage" \
+		"" \
+		"EXAMPLES: ansiweather -l Rzeszow,PL -u metric -s true -f 5 -d true" \
+		""
+	exit
+fi
+
+
+
+###[ Check if bc and jq are installed ]########################################
+
+jqpath=$(which jq)
+if [ "$jqpath" = "" ]
+then
+	echo "ERROR : Cannot find jq binary"
+	exit 69 # EX_UNAVAILABLE
+fi
+
+bcpath=$(which bc)
+if [ "$bcpath" = "" ]
+then
+	echo "ERROR : Cannot find bc binary"
+	exit 69 # EX_UNAVAILABLE
+fi
+
+
+
+###[ Set options that are not set from command line ]##########################
+
+# OpenWeatherMap API key
+[ -z "$api_key" ] && api_key=$(get_config "api_key" || echo "85a4e3c55b73909f42c6a23ec35b7147")
+
+# Location : example "Rzeszow,PL"
+[ -z "$location" ] && location=$(get_config "location" || echo "Rzeszow,PL")
+
+# System of Units : "metric" or "imperial"
+[ -z "$units" ] && units=$(get_config "units" || echo "metric")
+
+# Show forecast : How many days, example "5". "0" is standard output
+[ -z "$forecast" ] && forecast=$(get_config "forecast" || echo 0)
+
+# Show daylight : "true" or "false"
+[ -z "$daylight" ] && daylight=$(get_config "daylight" || echo false)
+
+# Display ANSI colors : "true" or "false"
+[ -z "$ansi" ] && ansi=$(get_config "ansi" || echo true)
+
+# Display symbols : "true" or "false" (requires an Unicode capable display)
+[ -z "$symbols" ] && symbols=$(get_config "symbols" || echo true)
+
+dateformat=$(get_config "dateformat" || echo "%a %b %d")
+timeformat=$(get_config "timeformat" || echo "%b %d %r")
+
+
+
+###[ Colors and characters ]###################################################
 
 background=$(get_config "background" || echo "\033[44m")
 text=$(get_config "text" || echo "\033[36;1m")
@@ -124,6 +156,8 @@ humidity_text=$(get_config "humidity_text" || echo "Humidity")
 pressure_text=$(get_config "pressure_text" || echo "Pressure")
 sunrise_text=$(get_config "sunrise_text" || echo "Sunrise")
 sunset_text=$(get_config "sunset_text" || echo "Sunset")
+forecast_text=$(get_config "forecast_text" || echo "forecast")
+
 
 
 ###[ Unicode Symbols for icons ]###############################################
@@ -131,120 +165,112 @@ sunset_text=$(get_config "sunset_text" || echo "Sunset")
 sun=$(get_config "sun" || echo "\033[33;1m\xe2\x98\x80")
 moon=$(get_config "moon" || echo "\033[36m\xe2\x98\xbd")
 clouds=$(get_config "clouds" || echo "\033[37;1m\xe2\x98\x81")
-rain=$(get_config "rain" || echo "\xe2\x98\x94")
+rain=$(get_config "rain" || echo "\033[37;1m\xe2\x98\x94")
 fog=$(get_config "fog" || echo "\033[37;1m\xe2\x96\x92")
 mist=$(get_config "mist" || echo "\033[34m\xe2\x96\x91")
 haze=$(get_config "haze" || echo "\033[33m\xe2\x96\x91")
 snow=$(get_config "snow" || echo "\033[37;1m\xe2\x9d\x84")
-thunderstorm=$(get_config "thunderstorm" || echo "\xe2\x9a\xa1")
+thunderstorm=$(get_config "thunderstorm" || echo "\033[33;1m\xe2\x9a\xa1")
 
 
 
 ###[ Fetch Weather data ]######################################################
 
-api_cmd=$([[ $forecast != 0 ]] && echo "forecast/daily" || echo "weather")
-weather=$($fetch_cmd "http://api.openweathermap.org/data/2.5/$api_cmd?q=$location&units=$units")
+api_cmd=$([ "$forecast" != 0 ] && echo "forecast/daily" || echo "weather")
+
+if [ "$location" -gt 0 ] 2> /dev/null
+then
+	# Location is all numeric
+	weather=$($fetch_cmd "http://api.openweathermap.org/data/2.5/$api_cmd?id=$location&units=$units&appid=$api_key")
+else
+	# Location is a string
+	location=$(echo "$location" | sed "s/ /_/g")
+	weather=$($fetch_cmd "http://api.openweathermap.org/data/2.5/$api_cmd?q=$location&units=$units&appid=$api_key")
+fi
 
 if [ -z "$weather" ]
 then
 	echo "ERROR : Cannot fetch weather data"
-	exit
+	exit 75 # EX_TEMPFAIL
 fi
 
-status_code=$(echo $weather | jq -r '.cod')
+status_code=$(echo "$weather" | jq -r '.cod' 2>/dev/null)
 
-if [ $status_code != 200 ]
+if [ "$status_code" != 200 ]
 then
 	echo "ERROR : Cannot fetch weather data for the given location"
-	exit
+	exit 69 # EX_UNAVAILABLE
 fi
 
 
 
 ###[ Process Weather data ]####################################################
 
-function epoch_to_date {
-	if date -j -r $1 +"%a %b %d" > /dev/null 2>&1; then
+epoch_to_date() {
+	if date -j -r "$1" +"%a %b %d" > /dev/null 2>&1; then
 		# BSD
-		ret=$(date -j -r $1 +"%a %b %d")
+		ret=$(date -j -r "$1" +"$dateformat")
 	else
 		# GNU
-		ret=$(date -d @$1 +"%a %b %d")
+		ret=$(date -d "@$1" +"$dateformat")
 	fi
-	echo $ret
+	echo "$ret"
 }
 
-if [ $forecast != 0 ]
+if [ "$forecast" != 0 ]
 then
-	city=$(echo $weather | jq -r '.city.name')
-	flength=$(echo $weather | jq '.list | length')
-	forecast=$([[ $forecast -gt $flength ]] && echo $flength || echo $forecast)
-	days=()
-	dates=()
-	lows=()
-	highs=()
-	humidity=()
-	pressure=()
-	sky=()
-	for i in $(seq 0 $(($forecast-1)))
-	do
-		days+=("$(echo $weather | jq ".list[$i]")")
-		dates+=("$(epoch_to_date $(echo ${days[$i]} | jq -r '.dt'))")
-		lows+=("$(printf "%0.0f" $(echo ${days[$i]} | jq -r '.temp.min'))")
-		highs+=("$(printf "%0.0f" $(echo ${days[$i]} | jq -r '.temp.max'))")
-		humidity+=("$(echo ${days[$i]} | jq -r '.humidity')")
-		pressure+=("$(echo ${days[$i]} | jq -r '.pressure')")
-		sky+=("$(echo ${days[$i]} | jq -r '.weather[0].main')")
-	done
+	city=$(echo "$weather" | jq -r '.city.name')
+	flength=$(echo "$weather" | jq '.list | length')
+	forecast=$([ "$forecast" -gt "$flength" ] && echo "$flength" || echo "$forecast")
 else
-	city=$(echo $weather | jq -r '.name')
-	temperature=$(printf '%.0f' $(echo $weather | jq '.main.temp'))
-	humidity=$(echo $weather | jq '.main.humidity')
-	pressure=$(echo $weather | jq '.main.pressure')
-	sky=$(echo $weather | jq -r '.weather[0].main')
-	sunrise=$(echo $weather | jq '.sys.sunrise')
-	sunset=$(echo $weather | jq '.sys.sunset')
-	wind=$(echo $weather | jq '.wind.speed')
-	azimuth=$(echo $weather | jq '.wind.deg')
+	city=$(echo "$weather" | jq -r '.name')
+	temperature=$(echo "$weather" | jq '.main.temp' | xargs printf "%.0f")
+	humidity=$(echo "$weather" | jq '.main.humidity')
+	pressure=$(echo "$weather" | jq '.main.pressure')
+	sky=$(echo "$weather" | jq -r '.weather[0].main')
+	sunrise=$(echo "$weather" | jq '.sys.sunrise')
+	sunset=$(echo "$weather" | jq '.sys.sunset')
+	wind=$(echo "$weather" | jq '.wind.speed')
+	azimuth=$(echo "$weather" | jq '.wind.deg')
 fi
 
 
 
 ###[ Process Wind data ]#######################################################
 
-declare -a directions
-directions=(N NNE NE ENE E ESE SE SSE S SSW SW WSW W WNW NW NNW)
+set -- N NNE NE ENE E ESE SE SSE S SSW SW WSW W WNW NW NNW
 
-if [ $forecast = 0 ]
+if [ "$forecast" = 0 ]
 then
-	direction=${directions[$(echo "($azimuth + 11.25)/22.5 % 16" | bc)]}
+	shift "$(echo "scale=0; ($azimuth + 11.25)/22.5 % 16" | bc)"
+	direction=$1
 fi
 
 
 
 ###[ Process Sunrise and Sunset data ]#########################################
 
-function epoch_to_time {
-	if date -j -r $1 +"%r" > /dev/null 2>&1; then
+epoch_to_time() {
+	if date -j -r "$1" +"%r" > /dev/null 2>&1; then
 		# BSD
-		ret=$(date -j -r $1 +"%b %d %r")
+		ret=$(date -j -r "$1" +"$timeformat")
 	else
 		# GNU
-		ret=$(date -d @$1 +"%b %d %r")
+		ret=$(date -d "@$1" +"$timeformat")
 	fi
-	echo $ret
+	echo "$ret"
 }
 
-if [ $forecast = 0 ]
+if [ "$forecast" = 0 ]
 then
 	if [ -n "$sunrise" ]
 	then
-		sunrise_time=$(epoch_to_time $sunrise)
+		sunrise_time=$(epoch_to_time "$sunrise")
 	fi
 
 	if [ -n "$sunset" ]
 	then
-		sunset_time=$(epoch_to_time $sunset)
+		sunset_time=$(epoch_to_time "$sunset")
 	fi
 fi
 
@@ -254,14 +280,14 @@ fi
 
 now=$(date +%s)
 
-if [ $forecast != 0 ]
+if [ "$forecast" != 0 ]
 then
 	period="none"
 else
 	if [ -z "$sunset" ] || [ -z "$sunrise" ]
 	then
 		period="day"
-	elif [ $now -ge $sunset ] || [ $now -le $sunrise ]
+	elif [ "$now" -ge "$sunset" ] || [ "$now" -le "$sunrise" ]
 	then
 		period="night"
 	else
@@ -278,13 +304,16 @@ case $units in
 		scale="°C"
 		speed_unit="m/s"
 		pressure_unit="hPa"
-		pressure=$(printf '%.0f' $pressure)
+		pressure=$(echo "$pressure" | xargs printf "%.0f")
 		;;
 	imperial)
 		scale="°F"
 		speed_unit="mph"
 		pressure_unit="inHg"
-		pressure=$(printf '%.2f' $(echo "$pressure*0.0295" | bc))
+		if [ "$forecast" = 0 ]
+		then
+			pressure=$(echo "$pressure*0.0295" | bc | xargs printf "%.2f")
+		fi
 		;;
 esac
 
@@ -292,21 +321,21 @@ esac
 
 ###[ Set icons ]###############################################################
 
-function get_icon {
+get_icon() {
 	case $1 in
 		Clear)
 			if [ $period = "night" ]
 			then
 				echo "$moon "
 			else
-				echo "$sun  "
+				echo "$sun "
 			fi
 			;;
 		Clouds)
-			echo "$clouds  "
+			echo "$clouds "
 			;;
 		Rain)
-			echo "$rain  "
+			echo "$rain "
 			;;
 		Fog)
 			echo "$fog "
@@ -321,7 +350,7 @@ function get_icon {
 			echo "$snow "
 			;;
 		Thunderstorm)
-			echo "$thunderstorm  "
+			echo "$thunderstorm "
 			;;
 	esac
 }
@@ -330,37 +359,49 @@ function get_icon {
 
 ###[ Display current Weather ]#################################################
 
-if [ $forecast != 0 ]
+if [ "$forecast" != 0 ]
 then
-	output="$background$text $city forecast $text$delimiter "
-	for i in $(seq 0 $(($forecast-1)))
+	output="$background$text $city $forecast_text $text$delimiter "
+
+	i=0
+	while [ $i -lt "$forecast" ]
 	do
+		day=$(echo "$weather" | jq ".list[$i]")
+		date=$(epoch_to_date "$(echo "$day" | jq -r '.dt')")
+		low=$(echo "$day" | jq -r '.temp.min' | xargs printf "%.0f")
+		high=$(echo "$day" | jq -r '.temp.max' | xargs printf "%.0f")
+
 		icon=""
-		if [ $symbols = true ]
+		if [ "$symbols" = true ]
 		then
-			icon="$(get_icon ${sky[$i]})"
+			sky=$(echo "$day" | jq -r '.weather[0].main')
+			icon=$(get_icon "$sky")
 		fi
-		output="$output$text${dates[$i]}: $data${highs[$i]}$text/$data${lows[$i]} $scale $icon"
-		if [ $i -lt $(($forecast-1)) ]
+
+		output="$output$text$date: $data$high$text/$data$low $scale $icon"
+		if [ $i -lt $((forecast-1)) ]
 		then
 			output="$output$dashes "
 		fi
+
+		i=$((i + 1))
 	done
-	output="$output\033[0m"
-	echo -e "$output"
 else
-	if [ $symbols = true ]
+	if [ "$symbols" = true ]
 	then
-		icon="$(get_icon $sky)"
+		icon="$(get_icon "$sky")"
 	fi
-	output="$background$text $greeting_text $city $delimiter$data $temperature $scale $icon$dashes$text $wind_text $delimiter$data $wind $speed_unit $direction $dashes$text $humidity_text $delimiter$data $humidity % $dashes$text $pressure_text $delimiter$data $pressure $pressure_unit"
+	output="$background$text $greeting_text $city $delimiter$data $temperature $scale $icon$dashes$text $wind_text $delimiter$data $wind $speed_unit $direction $dashes$text $humidity_text $delimiter$data $humidity %% $dashes$text $pressure_text $delimiter$data $pressure $pressure_unit "
 
-	if [ $daylight = true ]
+	if [ "$daylight" = true ]
 	then
-		output="$output $dashes$text $sunrise_text $delimiter$data $sunrise_time $dashes$text $sunset_text $delimiter$data $sunset_time"
+		output="$output $dashes$text $sunrise_text $delimiter$data $sunrise_time $dashes$text $sunset_text $delimiter$data $sunset_time "
 	fi
+fi
 
-	output="$output \033[0m"
-
-	echo -e "$output"
+if [ "$ansi" = true ]
+then
+	env printf "$output\033[0m\n"
+else
+	env printf "$output\n" | sed "s/$(printf '\033')\[[0-9;]*m//g"
 fi
